### ISSUE TITLE
place: investigate why for some objects the required dimension is 1 and for some others is 2

### ISSUE THREAD

**Issue by oscar-lima** [DFKI-NI/grasplan#10]
see: https://github.com/aprilprojecteu/grasplan/commit/c8a27e6fa6685c20a441b1e61b4aeb7fc40634b1

is it because the power drill mesh is transformed? I think I remember that when recording grasps this particular object also gave trouble...

**Comment by mintar** [comment]
No, it's because of the orientation of the mesh. The following image shows the power_drill_with_grip, the multimeter and the hot_glue_gun, and also the mesh coordinate system (I shifted the power drill and hot glue gun along the Y axis so they all fit into one image).

![snapshot00](https://github.com/aprilprojecteu/grasplan/assets/320188/ff0f4d3c-b939-422b-bb51-516a8bb9051e)

As you can see, the multimeter is in the "normal" orientation (according to ROS standards), i.e., the "upwards" axis of the mesh is `+z`, so the required dimension is the third dimension (index 2).

For the power drill and hot glue gun, the "upwards" axis of the mesh is `-y`, so the required dimension is the second dimension (index 1).

This is a bit unfortunate; the reason for this is that we just took the original meshes from the YCB object + mesh data set, and we intentionally kept the orientation so that the results from DOPE are comparable to the YCB-Video data set. Then for the hot glue gun I intentionally oriented it to be similar to the power drill, so that the grasps etc. are similar.
