### ISSUE TITLE
Grasplan placing only works with axis aligned planning scenes

### ISSUE THREAD

**Issue by jarkenau** [DFKI-NI/grasplan#11]
While setting up [mobipick_labs](https://github.com/DFKI-NI/mobipick_labs) in another part of our building, we noticed that Grasplan or more specifically the generation of place poses only works for axis aligned planning scenes.  @mintar came up with a quick fix for the demo (see [ai-demo-branch](https://github.com/aprilprojecteu/grasplan/commits/ai-day-demo/)) which involves generating the places poses in object coordinates (e.g from a table) and then transforming to map coordinates via a statically published transformation for earch object (see [here](https://github.com/DFKI-NI/mobipick_labs/commit/4e5fa2dd88a3068ef88213dedc9ac484cab7b5f3#diff-ca529245bd396ec3f7da8f5297e4e48779ceef20a0eb8846eebf9e4f2941740a)). In the long run we should fix this properly.

I'm willing to work on this, but probably need some guidance on how to best approach this.

cc @oscar-lima

**Comment by mintar** [comment]
If you want to take this on, that would be great!

Almost all the code is already there. The only missing piece of the puzzle is creating the TF transforms in code instead of the static_transform_publishers in the launch file.

I think it's best to switch to TF2 for the following.

The best place to start is here: http://wiki.ros.org/tf2/Tutorials

Especially [3. Writing a tf2 listener (Python)](http://wiki.ros.org/tf2/Tutorials/Writing%20a%20tf2%20listener%20%28Python%29) and [4. Adding a frame (Python)](http://wiki.ros.org/tf2/Tutorials/Adding%20a%20frame%20%28Python%29).

One way to do this would be to publish the transforms like they do in the "Adding a frame" tutorial. However, I think it would be better to just add the transform to our internal tf buffer instead of publishing it.

This code demonstrates what I mean:

```python
import rospy
import tf2_ros
import rospy
from geometry_msgs.msg import TransformStamped

rospy.init_node('my_node')
tf_buffer = tf2_ros.Buffer()
tf_listener = tf2_ros.TransformListener(tf_buffer)

t = TransformStamped()
t.header.frame_id = 'map'
t.child_frame_id = 'table_1'
t.transform.translation.x = 12.34
t.transform.rotation.w = 1.0
tf_buffer.set_transform_static(t, "my_authority")
tf_buffer.all_frames_as_string()
# prints 'Frame table_1 exists with parent map.\n'
bool(tf_buffer.can_transform('map', 'table_1', rospy.Time(0)))
# prints True
```

Some notes:

* `tf_buffer` and `tf_listener` should be `self.tf_buffer` and `self.tf_listener` respectively
* In TF2, you only interact directly with `tf_buffer`; the listener is only there to fill the buffer from the TF topic
* you can get the values for `t.transfrom` from `collision_object.pose.position.z` and so on
* since we are publishing a static transform, we can leave `t.header.stamp == 0`

Feel free to ask if something's unclear!

**Comment by oscar-lima** [comment]
Thank you both! Green light from my side :)
